### PR TITLE
Not getting mouse scroll wheel value

### LINKED ISSUE #71: 🐛Not getting mouse scroll wheel value
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the scroll wheel value for a mouse is always returning 0.  Figure out what is going on here.

**Things to consider:**
1. This might be a SILK.NET issue.  Research needs to be done to see if this is the case.  Possibly creating a prototype application to simply see if we can get a scroll wheel value at all.  This will verify if the issue is a SILK.NET issue or code issue.
2. This might been an issue in SILK v2.6.0 which is the current version being used. The latest version is v2.8.0.  If simply updating the SILK.NET nuget package to v2.8.0 might fix the issue.

Once the issue is discovered, you will also need to make sure that the Velaptor mouse scroll wheel value is being updated.  Investigation into the `GLWindowFacade` showed that the mouse scroll wheel value is not being updated.
This means that it will probably have to be updated in the `GLWindow_Update()` method because there is no event to subscribe to get mouse wheel value changes.  So the value will have to be picked up on every single update frame.

### Expected Behavior

The mouse scroll wheel value to be updated and have a value that makes sense.

### Steps To Reproduce

1. Create simple application
2. Consume Velaptor nuget package
3. Get the scroll wheel value
4. Observe that it is always set to 0

### Operating System

- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] Mac OS
- [ ] iOS

### If you know OS bug occurred on, enter OS version here

Windows 10 21H1 (OS Build 19043.1165)

**NOTE:** Other systems have not been checked or tested for this bug.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by CalvinWilkinson**
<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>

<h2 style="font-weight:bold" align="center">✅Development Checklist✅</h2>

<details open><summary>🌳Branching🌳</summary>

Does the name of the head(source) branch for this pull request have the correct **_preview feature branch_** syntax?

Syntax: _preview/feature/&lt;issue-id&gt;-&lt;description&gt;_  
Example: _preview/feature/123-my-preview-change_
- [x] Yes
- [ ] No

Does the name of the base(target) branch for this pull request have the correct **_preview branch_** syntax?

Syntax: _preview/v&lt;major-number&gt;.&lt;minor-number&gt;.&lt;patch-number&gt;-preview.&lt;prev-number&gt;_  
Example: _preview/v1.2.3-preview.4_
- [x] Yes
- [ ] No

Is the head(source) branch for this pull request created from a branch with the correct **_preview branch_** syntax?

Syntax: _preview/v&lt;major-number&gt;.&lt;minor-number&gt;.&lt;patch-number&gt;-preview.&lt;prev-number&gt;_  
Example: _preview/v1.2.3-preview.4_
- [x] Yes
- [ ] No
</details>

<details open><summary>🐛Bugs🐛</summary>

Contains Bug Fix(es)
- [x] Yes
  - [x] A bug-label label has been added to the pull request.
- [ ] No
</details>

<details open><summary>💣Breaking Change(s)💣</summary>

Contains [breaking change(s)](https://docs.microsoft.com/en-us/dotnet/core/compatibility/#modifications-to-the-public-contract)
- [ ] Yes
  - [ ] A breaking-change-label label has been added to the pull request.
- [x] No
</details>

<details open><summary>✨Enhancements✨</summary>

Contains enhancement(s) that add a feature or behavior.
- [x] Yes
  - [x] An enhancement-label label has been added to the pull request.
- [ ]  No
</details>

<details open><summary>⚙️Workflow (CI/CD) Changes⚙️</summary>

Contains changes to workflow files. These changes can only be done by the project maintainers.
- [ ] Yes
  - [ ] A workflow-label label has been added to the pull request.
- [x] No
</details>

<details open><summary>📃Documentation Updates📃</summary>

Contains changes that require updates to existing **_code_** and/or **_Velaptor product_** documentation.
- [ ] Yes
  - [ ] I have updated the documentation accordingly.
    - Choose the type of documentation.
    - [ ] Code Documentation
      - [ ] A documentation-code-label label has been added to the pull request.
    - [ ] Product Documentation
      - [ ] A documentation-product-label label has been added to the pull request.
- [x] No
</details>

<details open><summary>🧪Unit Testing🧪</summary>

My change requires unit tests to be written.
- [x] Yes
- [ ] No
</details>

<details open><summary>🧪Manual Testing🧪</summary>

I have manually tested my changes using the project named **_VelaptorTesting_**.
- [x] Yes
- [ ] No
</details>

<h2 style="font-weight:bold" align="center">✅Code Review Checklist✅</h2>

- [x] Pull request title matches the title of the linked issue.
- [x] Associated issue exists and is linked to this pull request.
  - One issue per pull request.
- [x] My code follows the coding style of this project.
  - The style is enforced by the *.editorconfig* files in the project and displayed as warnings.  If there is an edge case with a coding style that should be ignored or changed, reach out, and let's discuss it.
- [x] A preview-label label has been added to the pull request.
- [x] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vise-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - This does not mean that the tests pass in both the local and CI environment.
  - Status checks run for this pull request when merging into the **_preview/v\*.\*.\*-preview.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

### CODE REVIEW

File: Velaptor/Input/Mouse.cs [hunk 1]
```diff
@@ -15,13 +15,15 @@ public class Mouse : IMouseInput<MouseButton, MouseState>
...
         private static int scrollWheelValue;
+        private static MouseScrollDirection mouseScrollDirection;
 
         /// <summary>
         /// Gets the current state of the mouse.
         /// </summary>
         /// <returns>The state of the mouse.</returns>
         public MouseState GetState()
         {
+            // TODO: Check to see if we need to check '<='.  Instead use '<'
```
Comment (CalvinWilkinson) [inline Velaptor/Input/Mouse.cs:26]: Remove comment.

No need to do what the TODO comment instructs.  Mouse and keyboard functionality are going to be reworked in a future release

File: Velaptor/OpenGL/GLWindowFacade.cs [hunk 2]
```diff
@@ -406,16 +439,16 @@ private void GLMouseMove_MouseMove(IMouse mouse, Vector2 position)
         }
 
         /// <summary>
-        /// Invoked when any mouseInput buttons transition from the up position to the down position.
+        /// Invoked when the any of the mouse buttons are pressed into the down position over the window.
```
Comment (CalvinWilkinson) [inline Velaptor/OpenGL/GLWindowFacade.cs:442]: Refactor comment

```suggestion
        /// Invoked when any of the mouse buttons are pressed into the down position over the window.
```

File: Velaptor/OpenGL/GLWindowFacade.cs [hunk 3]
```diff
@@ -406,16 +439,16 @@ private void GLMouseMove_MouseMove(IMouse mouse, Vector2 position)
...
         /// </summary>
-        /// <param name="mouse">The system mouseInput.</param>
+        /// <param name="mouse">The system mouse object.</param>
         /// <param name="button">The button that was pushed down.</param>
         private void GLMouseInput_MouseDown(IMouse mouse, SilkMouseButton button) => this.mouseInput.SetState((VelaptorMouseButton)button, true);
 
         /// <summary>
-        /// Invoked when any mouseInput buttons transition from the down position to the up position.
+        /// Invoked when the any of the mouse buttons are released from the down position into the up position over the window.
```
Comment (CalvinWilkinson) [inline Velaptor/OpenGL/GLWindowFacade.cs:449]: Refactor comment

```suggestion
        /// Invoked when any of the mouse buttons are released from the down position into the up position over the window.
```

**Review by CalvinWilkinson — COMMENTED** [review]
Requesting changes
