### PR TITLE
🚀Release To Preview - v1.0.0-preview.5

### LINKED ISSUE #84: 🚧Improve font system
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

## Description

Improve the font system

### **Issue 1 (Font Loading):**
Currently, fonts are only loaded in the _**Content**_ directory path.  We need a way to search, find, and load system fonts.  
This is going to be different per operating system.  Create a dir path resolver to search and find system fonts for _**Windows**_.  Once this is complete, this will provide a foundation for other operating system font loading.  The operating system must be detected, then the proper resolver implementation injected into the `FontLoader`.  The loader must be able to search and find system fonts and return a list of all the fonts of the different styles for each font style. 

**Example:**
If the requested font is _**TimesNewRoman**_, then all 3 different font files for Regular, Bold, Italic, or of the correct style combination should be returned.  Currently it is unknown how performant the loading and creating of fonts will be because the font loading process creates a texture atlas during runtime.  

Another thing to consider is that if we are going to load system fonts instead of from the content location, this means that loading fonts by file name is not an approach we should take.  When loading fonts, we should load fonts by a font family name with font settings.  This means that we need to look into the **_FreeType_** library and see if we can find out what the font family is as well as the style. This will be used to check each file to see if it matches the font family and style when resolving font paths with the resolvers.

### **Issue 2 (Combined Font Style Rendering):**
A font with a combined style is itself a different font file.  Each font with a set style always has its own file.  

**Example:**
If the user requests the font family of **Times New Roman** with a style set to bold AND italic, this would actually be a completely separate file then for the **Times New Roman** bold font family.

**Windows File Examples:**
NOTE: These are located in the path _**C:\Windows\Fonts\**_ directory
**Times New Roman (Bold) File Name** --> timesbd.ttf
**Times New Roman (Bold & Italic)** --> timesbi.ttf

### **Issue 3 (Fonts That Do Not Exist):**
Currently there is a different font file for each style or combination of styles.  This means that if a bold font file exists but an italic one does not exist, then italic cannot be loaded when the person switches to another font style during runtime.  This has to be handled gracefully.  Throw a **FontDoesNotExistException** if this occurs.

Need to setup regular, bold, italic, and bold italic _**Times New Roman**_ fonts as an embedded resource and then build a service to pull the fonts out for loading and use. This will be the default font just in case a font is not found, or a font error occurs. 

### **Issue 4 (Font Settings):**
Currently, there is a requirement to have a JSON file that contains various font settings such as style and size.  This concept and everything related need to be removed.  The reason for this is due to the change in how fonts will be loaded.  Since it is currently required to have a JSON file, that means loading _**system**_ fonts would also require a JSON file and it would have to exist in the content directory.  This does not align with the direction of changes we want to make.

Change the `ContentLoader` class and other references using it to take in font settings as parameters such as size, style and font family.  This will also require changes to the `ContentLoader.Load<T>(string)` method by adding generic constraints to all of the other `IContent` types _**EXCEPT**_ `IFont`.  Create an overload method to the `ContentLoader` class and `IContentLoader` interface that should be constrained to only the `IFont` type to make sure that the font load overload method does not have to deal with other content types.  This overload method will have the additional font setting parameters.

**Overloaded Load Font Method Signature:**
`Load<T>(string family, int size = 12, FontStyle style = FontStyle.Regular) where T : class, IFont`

### **Research**
- [x] See if **FreeType** has the ability to detect which font style a font file is
    - It does have the ability.  This can be pulled right from the `FT_Face_Rec` type.  Refer to the link below for more info
        - [Get Font Style](https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_facerec)

---

### **Change font loading services**
- [x] Move all font related types in the `Velaptor.Content` namespace to `Velaptor.Content.Font`
- [x] Create a new `WindowsFontPathResolver` implementation of the `IPathResolver` interface
    - This will be used to resolve the dir path to the windows system fonts
- [x] Refactor the `FontPathResolver` class name to be named `ContentFontPathResolver`
    - ⚠️NOTE⚠️ This will be used to resolve to the content path that lives in the same location as the executable
    - This service will be used in the new service to first check for fonts in the content directory before checking the system
    - This will get injected into the new service that has the name `FontPathResolver` which is the new name of the class above.  Which used to be `FontPathResolver`
- [x] Create a new service named `FontPathResolver` that will take in other resolvers to resolve font dir paths
    - ⚠️NOTE⚠️ This is the new service but is using the old service name that is now `ContentFontPathResolver` and the `WindowsFontPathResolver` and `ContentFontPathResolver` will get injected into this server.
    - [x] Inject the `IPlatform` into this service
    - [x] Inject and use the new `ContentFontPathResolver` for resolving the dir path to a font in the root content location
    - [x] Inject and use the new `WindowsFontPathResolver`
        - Resolves the dir path to windows system fonts if no fonts were found in the content path first
- [x] Refactor the `ContentLoaderFactory` class to inject the correct system font path resolver implementation based on the current system. 

---

### **Font Loading**
- [x] Setup the _**Times New Roman**_ fonts of regular, bold, italic, and bold italic as an embedded resource.
    - [x] Refactor `EmbeddedResourceLoaderService` `IEmbeddedResourceLoaderService` types
        - [x] Rename the `EmbeddedResourceLoaderService` class to `TextResourceLoaderService`
        - [x] Make the interface `IEmbeddedResourceLoaderService` a generic that determines the type of data returned by the `LoadResource()` method.
    - [x] Create new `IEmbeddedResourceLoaderService` implementation named `EmbeddedFontResourceService`
        - [x] This service will check to see if the resource exists and throw and exception if it does not.
        - [x] This service will return a `Stream` object that can be used to copy the embedded font file to the Font content directory
    - [x] Setup the `FontLoader` implementation to check and see if the default embedded fonts have been extracted, and if not, extract the default fonts embedded resources into the Content/Fonts directory.
    - [x] Update the `Label` class to request the **_TimesNewRoman-Regular_** font which is a default extracted embedded resource font.
- [x] Check to see if the _**FreeType**_ library has a way to check a font files family and style.  If so, add the proper implementations to the native interop system to take advantage of these checks so the resolvers can use them to find the proper font files.
- [x] When switching between one font style and another, throw a custom exception named `FontDoesNotExistException` if the font does not have that particular style
- [x] Add a property to the `Font` and `IFont` types named `AvailableStyles` that is a list of all of the styles available for the currently loaded font.
- [x] Gracefully unload one font and load another.
- [x] Load the different font required when the user changes the value of the `IFont.Style` property
- [x] Load the different font required when the user changes the value of the `IFont.Size` property
- [x] **Measure** and **improve** the performance of the font loading to understand if switching to different font styles is viable during runtime
- [x] Build caching system that the texture loading process can take advantage of
- [x] Build caching system that the font loading process can take advantage of

---

### **Direct Texture File Loading**

These are changes for the `TextureLoader` class for loading textures.  These will enable the ability to create texture atlas textures from font files, or directly from _**.png**_ files.  This also adds special syntax to the incoming value for bringing in extra data like the font size for creating font atlas textures.  This is required because each font size will be a different texture.

- [x] Process texture files differently depending on if the incoming name is a file path or not a file path
    - [x] Maintain the functionality of the value of `name` not being a file path.  This will signify that the texture needs to be loaded from the application's texture content directory and the file path will be figured out using the `texturePathResolver` injected into the `TextureLoader`
    - [x] If `name` is a full file path, then the resolver will not be used, and the image created using this path
    - [x] Check if the file exists and if not, throws an exception
        - [x] Add exception documentation to the load method for this exception
    - [x] Throw an exception if the file type is **NOT** a _**.png**_ or _**.ttf**_ file
        - [x] Add exception documentation to the load method for this exception
    - [x] If the value of `name` is a _**.ttf**_ true type font file, then it needs to be parsed to see if the font size is included withing the value of `name`.
        - Font file size syntax: C:\Windows\Fonts\times.ttf|size:22

---

### **Misc**
- [x]  Change the data type of the `IFont.Size` property and all required uses and referecenes from `int` to `uint`
    - 💣Breaking Change
- [x] Add new property to `IFont` and `Font` of the new enum type below called `FontSource` that shows if the font was loaded from the system vs the application content directory
    ```` cs
    /// <summary>
    /// Represents the source of where a font was loaded from.
    /// </summary>
    /// <remarks>
    ///     When loading fonts, the font that is attempting to be loaded will be
    ///     checked for its existence in the application's content directory first.
    ///     If the font does not exist there, then the font will be checked for
    ///     its existence in the system.  If the font does not exist in the application's
    ///     content directory or the system, then an exception will be thrown.
    /// </remarks>
    public enum FontSource
    {
        /// <summary>
        /// Loaded from the application's content directory.
        /// </summary>
        Content,

        /// <summary>
        /// Loaded from the system.
        /// </summary>
        System,
    }
    ````

- [x] `IFont.GetAvailableGlyphCharacters()` method
    - 💣 Breaking change
- [x] Unit tests added

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [x] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

### Issue Dependencies

_No response_

### Related Work

_No response_

### PR DESCRIPTION
**Pull request by CalvinWilkinson**
## Preview Release PR Description
This pull request performs a preview release for version **_v1.0.0-preview.5_**

## How Has This Been Tested?
- [x] Testing Application (Manual)
- [ ] No Testing Required

---

## Development Checklist:
**Types Of Changes:**
- Bug Fix(es)
  - [ ] A **_bug_** label has been added to the PR
- [x] Contains breaking change(s)
  - 💡 This would force library users to change their code.  This would involve a public facing API change, behavior that would force a change to the users code base, or even an update in behavior that could force a change to the library users code base.  Sometimes this it is unclear if the change is a breaking change.  If it is unclear, reach out so we can discuss and investigate if it is indeed a breaking change.
- Additional feature and/or behavior added.
  - [x] Yes
    - [x] An **_enhancement_** label has been added to the PR
  - [ ] No
- I have changes related to workflows (CI/CD)
  - 💡 These kinds of changes are only done by the project owner and maintainers that are allowed to make changes to workflows
  - [ ] Yes
    - [ ] A **_workflow_** label has been added to the PR
  - [x] No

**Documentation:**
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
  - [x] A **_documentation_** label has been added to the PR

**Testing:**
- My change requires unit tests to be written
  - [x] Yes
    - [x] I have added tests to cover my changes.
  - [ ] No
- [x] I have manually tested my changes to the best of my ability
  - NOTE: This can be done by using the included testing application

---

## Review Checklist:

- [x] PR title matches the example below with the correct version
  * 💡 **Example:** 🚀Release To Preview - v1.2.3-preview.4
- [x] The **_[add version here]_** text in the PR description replaced with the version.
- [x] Issues exist and are linked to this PR.
- [x] My code follows the coding style of this project.
  - 💡 This is enforced by the *.editorconfig* files in the project and displayed as warnings.  If there is an edge case with coding style that should be ignored or changed, reach out and lets discuss it.
- [x] All tests passed locally.
  - 💡 Status checks are put in place to run unit tests every single time a change is pushed to a PR.  This does not mean that the tests pass in both the local and CI environment.
- [x] Update library version by updating the **_\<Version/\>_** and **_\<FileVersion/\>_** tags in the **_Velaptor_** **_.csproj_** file.
  - 💡 Every change to a PR will run a status check to confirm that the version has the correct syntax, a tag does not exist, and that it has not already been published to nuget.org
  - 💡 Make sure to add the **_-preview.\<number\>_** syntax to the end of the version
    - **Example:**
      ``` html
      <Version>1.2.3-preview.4</Version>
      <FileVersion>1.2.3-preview.4</FileVersion>
      ```
- [x] I have updated the release notes by creating a new preview release notes file and adding it to the **_./Documentation/ReleaseNotes/PreviewReleases_** folder
- [x] A **_preview_** label has been added to the PR

### CODE REVIEW

**Comment by CalvinWilkinson** [comment]
@kselena This PR is ready for its documentation review.  😃

**Comment by CalvinWilkinson** [comment]
@kselena Could you by chance please review the release notes?  I might have not pushed them to remote yet by the time you release this but figured I would just let you know now so it is not missed.

The name of the file will be _**Release-Notes-v1.0.0-preview.5.md**_

File: Velaptor/IoC.cs [hunk 1]
```diff
@@ -79,20 +83,34 @@ private static void SetupContainer()
...
             IoCContainer.Register<IGLInvokerExtensions, GLInvokerExtensions>(Lifestyle.Singleton);
 
             IoCContainer.Register<GLFWMonitors>(suppressDisposal: true);
 
-            IoCContainer.Register<IGLInvoker, GLInvoker>(Lifestyle.Singleton);
             IoCContainer.Register<IGLFWInvoker, GLFWInvoker>(Lifestyle.Singleton);
             IoCContainer.Register<IGameWindowFacade, GLWindowFacade>(Lifestyle.Singleton, suppressDisposal: true);
+
+            IoCContainer.Register<IFreeTypeInvoker, FreeTypeInvoker>(Lifestyle.Singleton);
+            IoCContainer.Register<IFontService, FontService>(Lifestyle.Singleton);
```
Comment (CalvinWilkinson) [inline Velaptor/IoC.cs:103]: Move to `SetupServices()` method

```suggestion
            IoCContainer.Register<IFontService, FontService>(Lifestyle.Singleton);
```

File: Velaptor/IoC.cs [hunk 2]
```diff
@@ -79,20 +83,34 @@ private static void SetupContainer()
...
+        }
+
+        private static void SetupCaching() => IoCContainer.Register<IDisposableItemCache<string, ITexture>, TextureCache>(Lifestyle.Singleton);
+
+        private static void SetupFactories()
```
Comment (CalvinWilkinson) [inline Velaptor/IoC.cs:108]: Add code docs to `SetupFactories()` method

File: Velaptor/IoC.cs [hunk 3]
```diff
@@ -79,20 +83,34 @@ private static void SetupContainer()
...
 
-            IoCContainer.Register<IGLInvoker, GLInvoker>(Lifestyle.Singleton);
             IoCContainer.Register<IGLFWInvoker, GLFWInvoker>(Lifestyle.Singleton);
             IoCContainer.Register<IGameWindowFacade, GLWindowFacade>(Lifestyle.Singleton, suppressDisposal: true);
+
+            IoCContainer.Register<IFreeTypeInvoker, FreeTypeInvoker>(Lifestyle.Singleton);
+            IoCContainer.Register<IFontService, FontService>(Lifestyle.Singleton);
+        }
+
+        private static void SetupCaching() => IoCContainer.Register<IDisposableItemCache<string, ITexture>, TextureCache>(Lifestyle.Singleton);
```
Comment (CalvinWilkinson) [inline Velaptor/IoC.cs:106]: Add code docs to `SetupCaching()` method

File: Velaptor/PublicExtensionMethods.cs [hunk 4]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        ///             <item>Value of <c>C:/my-directory/my-file</c> will return <c>true</c></item>
+        ///             <item>Value of <c>C:/my-directory/.txt</c> will return <c>true</c></item>
+        ///         </list>
+        ///     </item>
+        /// </list>
+        /// </example>
+        /// <remarks>
+        ///     This does not check if the path actually exists.  This is for valid path syntax checks only.
+        /// </remarks>
+        public static bool IsInvalidFilePath(this string path) => !IsValidFilePath(path);
```
Comment (CalvinWilkinson) [inline Velaptor/PublicExtensionMethods.cs:399]: Refactor name to below and adjust usages and XML code comments as necessary

```suggestion
        public static bool HasInvalidFullFilePathSyntax(this string path) => !IsValidFilePath(path);
```

File: Velaptor/PublicExtensionMethods.cs [hunk 5]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        ///             <item>Value of <c>C:/my-directory/my-file</c> will return <c>false</c></item>
+        ///             <item>Value of <c>C:/my-directory/.txt</c> will return <c>false</c></item>
+        ///         </list>
+        ///     </item>
+        /// </list>
+        /// </example>
+        /// <remarks>
+        ///     This does not check if the path actually exists.  This is for valid path syntax checks only.
+        /// </remarks>
+        public static bool IsValidFilePath(this string path)
```
Comment (CalvinWilkinson) [inline Velaptor/PublicExtensionMethods.cs:337]: Refactor name to below and adjust usages and XML code comments as necessary

```suggestion
        public static bool HasValidFullFilePathSyntax(this string path)
```

File: Velaptor/PublicExtensionMethods.cs [hunk 6]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        ///     <item>Value of <c>C/my-dir/my-file.txt</c> will return <c>false</c>.</item>
+        ///     <item>Value of <c>//my-dir</c> will return <c>false</c>.</item>
+        ///     <item>Value of <c>./my-dir</c> will return <c>false</c>.</item>
+        ///     <item>Value of <c>../my-dir</c> will return <c>false</c>.</item>
+        /// </list>
+        /// </example>
+        /// <remarks>
+        ///     This does not check if the drive actually exists.  This is for valid path syntax checks only.
+        /// </remarks>
+        public static bool ContainsValidDrive(this string path)
```
Comment (CalvinWilkinson) [inline Velaptor/PublicExtensionMethods.cs:419]: Refactor name to below and adjust usages and XML code comments as necessary

```suggestion
        public static bool HasValidDriveSytax(this string path)
```

File: Velaptor/PublicExtensionMethods.cs [hunk 7]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        /// <list type="number">
+        ///     <item>Value of <c>C:/my-dir</c> will return <c>true</c>.</item>
+        ///     <item>Value of <c>C:/my-dir/</c> will return <c>true</c>.</item>
+        ///     <item>Value of <c>C:/my-dir/my-file.txt</c> will return <c>false</c>.</item>
+        /// </list>
+        /// </example>
+        /// <remarks>
+        ///     This does not check if the directory path actually exists.  This is for valid path syntax checks only.
+        /// </remarks>
+        public static bool IsFullyQualifiedDirPath(this string dirPath)
```
Comment (CalvinWilkinson) [inline Velaptor/PublicExtensionMethods.cs:459]: Refactor name to below and adjust usages and XML code comments as necessary

```suggestion
        public static bool HasValidFullDirPathSyntax(this string dirPath)
```

File: Velaptor/PublicExtensionMethods.cs [hunk 8]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        /// <example>
+        /// <list type="number">
+        ///     <item>Value of <c>C:/Windows</c> will return <c>false</c>.</item>
+        ///     <item>Value of <c>//my-share</c> will return <c>true</c>.</item>
+        /// </list>
+        /// </example>
+        /// <remarks>
+        ///     This does not check if the UNC directory path actually exists.  This is for valid path syntax checks only.
+        /// </remarks>
+        public static bool IsUNCPath(this string path)
```
Comment (CalvinWilkinson) [inline Velaptor/PublicExtensionMethods.cs:495]: Refactor name to below and adjust usages and XML code comments as necessary

```suggestion
        public static bool HasValidUNCPathSyntax(this string path)
```

File: Velaptor/Services/FontMetaDataParseResult.cs [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+        /// </summary>
+        public readonly bool IsValid;
+
+        /// <summary>
+        /// Gets the data before the metadata section.
+        /// </summary>
+        public readonly string MetaDataPrefix;
+
+        /// <summary>
+        /// Gets the meta data string.
```
Comment (CalvinWilkinson) [inline Velaptor/Services/FontMetaDataParseResult.cs:29]: Refactor as below.  **meta data** should be one word

```suggestion
        /// Gets the metadata string.
```

Search entire code base for **meta data** and replace with **metadata**

File: Velaptor/Services/IEmbeddedResourceLoaderService.cs [hunk 10]
```diff
@@ -5,15 +5,16 @@
...
-    /// Loads embedded text file resources.
+    /// Loads embedded file resources.
     /// </summary>
-    internal interface IEmbeddedResourceLoaderService
+    /// <typeparam name="TResourceType">The type of data being returned from the contents of the embedded resource.</typeparam>
+    internal interface IEmbeddedResourceLoaderService<out TResourceType>
     {
         /// <summary>
-        /// Load a text resources that matches the given <paramref name="name"/>.
+        /// Load an embedded resources that matches the given <paramref name="name"/>.
```
Comment (CalvinWilkinson) [inline Velaptor/Services/IEmbeddedResourceLoaderService.cs:14]: Refactor code docs as below

```suggestion
        /// Load embedded resources that match the given <paramref name="name"/>.
```

File: Velaptor/Content/Fonts/FontPathResolver.cs [hunk 11]
```diff
@@ -0,0 +1,149 @@
...
+        /// </returns>
+        /// <exception cref="NotImplementedException">Thrown if the current platform is not Windows.</exception>
+        public string ResolveFilePath(string contentName)
+        {
+            if (this.platform.CurrentPlatform != OSPlatform.Windows)
+            {
+                throw new NotImplementedException(OnlyWindowsSupportMessage);
+            }
+
+            var contentFilePath = this.contentFontPathResolver.ResolveFilePath(contentName);
```
[the remark this answers is not in the document]
Comment (CalvinWilkinson) [reply Velaptor/Content/Fonts/FontPathResolver.cs:123]: Cannot do this.  Did not notice that it was being used in multiple places.

File: Testing/VelaptorTests/Content/ContentLoaderTests.cs [hunk 12]
```diff
@@ -61,10 +55,10 @@ public void Load_WhenLoadingSounds_LoadsSound()
             var loader = CreateContentLoader();
```
Comment (kselena) [inline Testing/VelaptorTests/Content/ContentLoaderTests.cs:57]: Refactor method name 
```suggestion
        public void LoadSound_WhenLoadingSounds_LoadsSound()
```

File: Testing/VelaptorTests/Content/ContentLoaderTests.cs [hunk 13]
```diff
@@ -74,10 +68,10 @@ public void Load_WhenLoadingAtlasData_LoadsAtlasData()
...
```
Comment (kselena) [inline Testing/VelaptorTests/Content/ContentLoaderTests.cs:70]: Refactor method to match method to test
```suggestion
public void LoadAtlas_WhenLoadingAtlasData_LoadsAtlasData()
```

File: Testing/VelaptorTests/Content/ContentLoaderTests.cs [hunk 14]
```diff
@@ -87,92 +81,88 @@ public void Load_WhenLoadingFonts_LoadsFont()
...
```
Comment (kselena) [inline Testing/VelaptorTests/Content/ContentLoaderTests.cs:83]: Refactor method to match unit test
```suggestion
public void LoadFont_WhenLoadingFonts_LoadsFont()
```

File: Testing/VelaptorTests/Content/ContentLoaderTests.cs [hunk 15]
```diff
@@ -87,92 +81,88 @@ public void Load_WhenLoadingFonts_LoadsFont()
...
+            loader.LoadFont(FontContentName, 12);
 
             // Assert
-            this.mockFontLoader.Verify(m => m.Load(FontName), Times.Once());
+            this.mockFontLoader.Verify(m => m.Load($"{FontContentName}|size:12"), Times.Once());
         }
 
         [Fact]
-        public void Load_WhenLoadingUnknownContent_ThrowsException()
+        public void Unload_WhenUnloadingTextures_UnloadsTexture()
```
Comment (kselena) [inline Testing/VelaptorTests/Content/ContentLoaderTests.cs:92]: Refactor method name 
```suggestion
        public void UnloadTexture_WhenUnloadingTextures_UnloadsTexture()
```

File: Testing/VelaptorTests/Content/ContentLoaderTests.cs [hunk 16]
```diff
@@ -87,92 +81,88 @@ public void Load_WhenLoadingFonts_LoadsFont()
...
-            loader.Unload<ITexture>(TextureName);
+            loader.UnloadTexture(texture);
 
             // Assert
-            this.mockTextureLoader.Verify(m => m.Unload(TextureName), Times.Once());
+            this.mockTextureLoader.Verify(m => m.Unload(TextureContentName), Times.Once());
         }
 
         [Fact]
         public void Unload_WhenUnloadingSounds_UnloadsSound()
```
Comment (kselena) [inline Testing/VelaptorTests/Content/ContentLoaderTests.cs:111]: Refactor method name
```suggestion
        public void UnloadSound_WhenUnloadingSounds_UnloadsSound()
```

File: Testing/VelaptorTests/Content/ContentLoaderTests.cs [hunk 17]
```diff
@@ -87,92 +81,88 @@ public void Load_WhenLoadingFonts_LoadsFont()
...
-            loader.Unload<ISound>(SoundName);
+            loader.UnloadSound(sound);
 
             // Assert
-            this.mockSoundLoader.Verify(m => m.Unload(SoundName), Times.Once());
+            this.mockSoundLoader.Verify(m => m.Unload(SoundContentName), Times.Once());
         }
 
         [Fact]
         public void Unload_WhenUnloadingAtlasData_UnloadsAtlasData()
```
Comment (kselena) [inline Testing/VelaptorTests/Content/ContentLoaderTests.cs:130]: Refactor method name
```suggestion
        public void UnloadAtlas_WhenUnloadingAtlasData_UnloadsAtlasData()
```

**Review by kselena — CHANGES_REQUESTED** [review]

**Comment by CalvinWilkinson** [comment]
@kselena Here is the name of the markdown file that holds the release notes for v1.0.0-preview.5.  

**_Release-Notes-v1.0.0-preview.5.md_**

File: Velaptor/Exceptions/LoadEmbeddedResourceException.cs [hunk 18]
```diff
@@ -0,0 +1,44 @@
...
+            : base(message)
+        {
+        }
+
+        /// <summary>
+        /// Initializes a new instance of the <see cref="LoadEmbeddedResourceException"/> class.
+        /// </summary>
+        /// <param name="message">The exception message.</param>
+        /// <param name="innerException">
+        ///     The exception that is the cause of the current exception, or a
```
Comment (kselena) [inline Velaptor/Exceptions/LoadEmbeddedResourceException.cs:36]: Sentence structure
```suggestion
        ///     The cause of the current exception, or a
```

File: Velaptor/Exceptions/LoadEmbeddedResourceException.cs [hunk 19]
```diff
@@ -0,0 +1,44 @@
...
+        ///     null reference if no inner exception is specified.
```
Comment (kselena) [inline Velaptor/Exceptions/LoadEmbeddedResourceException.cs:37]: Sentence structure (SS will be used from now on)
```suggestion
        ///     null reference if no exception is specified.
```

File: Velaptor/Factories/PathResolverFactory.cs [hunk 20]
```diff
@@ -17,37 +20,87 @@ namespace Velaptor.Factories
...
+        /// <summary>
+        /// Creates a path resolver that resolves paths to fonts in the application's content directory.
+        /// </summary>
+        /// <returns>The resolver instance.</returns>
+        [SuppressMessage("ReSharper", "UnusedMember.Global", Justification = "Left here for future development.")]
+        public static IPathResolver CreateContentFontPathResolver() =>
+            contentFontPathResolver ??= new ContentFontPathResolver(IoC.Container.GetInstance<IDirectory>());
+
+        /// <summary>
+        /// Creates a path resolver that resolves paths to fonts in the systems font directory.
```
Comment (kselena) [inline Velaptor/Factories/PathResolverFactory.cs:61]: Grammar
```suggestion
        /// Creates a path resolver that resolves paths to fonts in the system's font directory.
```

File: Velaptor/Factories/PathResolverFactory.cs [hunk 21]
```diff
@@ -17,37 +20,87 @@ namespace Velaptor.Factories
...
         /// <summary>
         /// Creates a path resolver that resolves paths to sound content.
         /// </summary>
         /// <returns>The resolver to sound content.</returns>
+        [SuppressMessage("ReSharper", "UnusedMember.Global", Justification = "Left here for future development.")]
         public static IPathResolver CreateSoundPathResolver() =>
             soundPathResolver ??= new SoundPathResolver(IoC.Container.GetInstance<IDirectory>());
+
+        /// <summary>
+        /// Creates a path resolver that resolves paths to fonts in the windows font directory.
```
Comment (kselena) [inline Velaptor/Factories/PathResolverFactory.cs:99]: Grammar
```suggestion
        /// Creates a path resolver that resolves paths to fonts in the Windows font directory.
```
Is this Windows as in the OS or just a window?

File: Velaptor/Graphics/ImageData.cs [hunk 22]
```diff
@@ -41,9 +41,42 @@ namespace Velaptor.Graphics
...
         /// <param name="height">The height of the image.</param>
-        public ImageData(Color[,] pixels, uint width, uint height)
+        public ImageData(Color[,]? pixels, uint width, uint height)
         {
-            this.Pixels = pixels;
+            if (pixels is null)
+            {
+                this.Pixels = new Color[width, height];
+
+                // Make all the pixels white
```
Comment (kselena) [inline Velaptor/Graphics/ImageData.cs:50]: SS
```suggestion
                // Makes all pixels white.
```

File: Velaptor/InternalExtensionMethods.cs [hunk 23]
```diff
@@ -29,6 +29,39 @@ namespace Velaptor
     /// </summary>
     internal static class InternalExtensionMethods
     {
+        /// <summary>
+        /// Determines whether this string instance does not start with the specified character.
```
Comment (kselena) [inline Velaptor/InternalExtensionMethods.cs:33]: SS
```suggestion
        /// Determines whether or not this string instance starts with the specified character.
```

File: Velaptor/InternalExtensionMethods.cs [hunk 24]
```diff
@@ -29,6 +29,39 @@ namespace Velaptor
...
+        /// </summary>
+        /// <param name="stringToCheck">The string to check.</param>
+        /// <param name="value">The character to compare.</param>
+        /// <returns><c>true</c> if <paramref name="value"/> matches the beginning of this string; otherwise, <c>false</c>.</returns>
+        public static bool DoesNotStartWith(this string stringToCheck, char value) => !stringToCheck.StartsWith(value);
+
+        /// <summary>
+        /// Determines whether this string instance does not start with the specified string.
```
Comment (kselena) [inline Velaptor/InternalExtensionMethods.cs:41]: SS
```suggestion
Determines whether or not this string instance starts with the specified character.
```

File: Velaptor/InternalExtensionMethods.cs [hunk 25]
```diff
@@ -29,6 +29,39 @@ namespace Velaptor
...
+        /// </summary>
+        /// <param name="stringToCheck">The string to check.</param>
+        /// <param name="value">The string to compare.</param>
+        /// <returns><c>true</c> if <paramref name="value"/> matches the beginning of this string; otherwise, <c>false</c>.</returns>
+        public static bool DoesNotStartWith(this string stringToCheck, string value) => !stringToCheck.StartsWith(value);
+
+        /// <summary>
+        /// Determines whether the end of this string instance matches the specified character.
```
Comment (kselena) [inline Velaptor/InternalExtensionMethods.cs:49]: SS
```suggestion
        /// Determines whether or not the end of this string instance matches the specified character.
```

File: Velaptor/InternalExtensionMethods.cs [hunk 26]
```diff
@@ -29,6 +29,39 @@ namespace Velaptor
...
+        /// </summary>
+        /// <param name="stringToCheck">The string to check.</param>
+        /// <param name="value">The character to compare to the character at the end of this instance.</param>
+        /// <returns><c>true</c> if <paramref name="value"/> matches the end of this instance; otherwise, <c>false</c>.</returns>
+        public static bool DoesNotEndWith(this string stringToCheck, char value) => !stringToCheck.EndsWith(value);
+
+        /// <summary>
+        /// Determines whether the end of this string instance matches the specified string.
```
Comment (kselena) [inline Velaptor/InternalExtensionMethods.cs:57]: SS
```suggestion
        /// Determines whether or not the end of this string instance matches the specified string.
```

File: Velaptor/InternalExtensionMethods.cs [hunk 27]
```diff
@@ -29,6 +29,39 @@ namespace Velaptor
...
+        /// </summary>
+        /// <param name="stringToCheck">The string to check.</param>
+        /// <param name="value">The string to compare to the character at the end of this instance.</param>
+        /// <returns><c>true</c> if <paramref name="value"/> matches the end of this instance; otherwise, <c>false</c>.</returns>
+        [SuppressMessage("ReSharper", "UnusedMember.Global", Justification = "Kept for future development.")]
+        public static bool DoesNotEndWith(this string stringToCheck, string value) => !stringToCheck.EndsWith(value);
+
         /// <summary>
         /// Returns a value indicating whether the given file or directory path
```
Comment (kselena) [inline Velaptor/InternalExtensionMethods.cs:66]: SS
```suggestion
        /// Returns a value indicating whether or not the given file or directory path
```

File: Velaptor/InternalExtensionMethods.cs [hunk 28]
```diff
@@ -29,6 +29,39 @@ namespace Velaptor
...
         /// only contains a root drive path with no directories.
```
Comment (kselena) [inline Velaptor/InternalExtensionMethods.cs:67]: SS
```suggestion
        /// contains a root drive path with no directories.
```
Not sure if removing ONLY is appropriate.

File: Velaptor/NativeInterop/FreeType/FreeTypeInvoker.cs [hunk 29]
```diff
@@ -128,44 +110,17 @@ public void FT_Done_Face(IntPtr face)
...
-
-            FT.FT_Done_Face(this.facePtr);
-            FT.FT_Done_FreeType(this.libraryPtr);
-
-            this.isDisposed = true;
-            GC.SuppressFinalize(this);
-        }
-
         /// <summary>
         /// Creates n error message from the standard Free Type message.
```
Comment (kselena) [inline Velaptor/NativeInterop/FreeType/FreeTypeInvoker.cs:125]: Grammar
```suggestion
        /// Creates an error message from the standard FreeType message.
```

File: Velaptor/IoC.cs [hunk 30]
```diff
@@ -79,20 +83,39 @@ private static void SetupContainer()
         /// <summary>
         /// Setup container registration related to OpenGL.
```
Comment (kselena) [inline Velaptor/IoC.cs:84]: Grammar
```suggestion
        /// Sets up container registration related to OpenGL.
```

Comment (kselena) [inline Velaptor/IoC.cs:84]: Grammar
```suggestion
        /// Sets up container registration related to OpenGL.
```

File: Velaptor/IoC.cs [hunk 31]
```diff
@@ -79,20 +83,39 @@ private static void SetupContainer()
...
 
-            IoCContainer.Register<IGLInvoker, GLInvoker>(Lifestyle.Singleton);
             IoCContainer.Register<IGLFWInvoker, GLFWInvoker>(Lifestyle.Singleton);
             IoCContainer.Register<IGameWindowFacade, GLWindowFacade>(Lifestyle.Singleton, suppressDisposal: true);
+
+            IoCContainer.Register<IFreeTypeInvoker, FreeTypeInvoker>(Lifestyle.Singleton);
+        }
+
+        /// <summary>
+        /// Setup container registration related to caching.
```
Comment (kselena) [inline Velaptor/IoC.cs:106]: Spelling
```suggestion
        /// Sets up container registration related to caching.
```

File: Velaptor/IoC.cs [hunk 32]
```diff
@@ -79,20 +83,39 @@ private static void SetupContainer()
...
+        /// </summary>
+        private static void SetupCaching() => IoCContainer.Register<IDisposableItemCache<string, ITexture>, TextureCache>(Lifestyle.Singleton);
+
+        /// <summary>
+        /// Setup container registration related to factories.
```
Comment (kselena) [inline Velaptor/IoC.cs:111]: Spelling
```suggestion
        /// Sets up container registration related to factories.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 33]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        /// is a fully qualified path.
+        /// </summary>
+        /// <param name="path">The path to check.</param>
+        /// <returns><c>true</c> if valid.</returns>
+        /// <example>
+        /// <list type="number">
+        ///     <item>Value of <c>null</c> will return <c>false</c>.</item>
+        ///     <item><c>null</c> or <c>empty</c> will returns <c>false</c>.</item>
+        ///     <item>
+        ///         Start with a drive letter
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:317]: Grammar
```suggestion
        ///         Start with a drive letter.
```
This is really indented.  Is it supposed to be?

File: Velaptor/PublicExtensionMethods.cs [hunk 34]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        ///         <para>Value of <c>C:/</c> will return <c>true</c>.</para>
+        ///     </item>
+        ///     <item>
+        ///         Contain at least 1 directory
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:321]: Grammar
```suggestion
        ///         Contains at least 1 directory.
```
This is also very indented.

File: Velaptor/PublicExtensionMethods.cs [hunk 35]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        ///         <para>will return <c>true</c>: C:/my-directory</para>
+        ///     </item>
+        ///     <item>
+        ///         Must contain a file name with file extension
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:325]: Grammar
```suggestion
        ///         Must contain a file name with file extension.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 36]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        ///         <list type="bullet">
+        ///             <item>Value of <c>C:/my-directory/my-file.txt</c> will return <c>true</c>.</item>
+        ///             <item>Value of <c>C:/my-directory/my-file</c> will return <c>false</c></item>
+        ///             <item>Value of <c>C:/my-directory/.txt</c> will return <c>false</c></item>
+        ///         </list>
+        ///     </item>
+        /// </list>
+        /// </example>
+        /// <remarks>
+        ///     This does not check if the path actually exists.  This is for valid path syntax checks only.
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:335]: SS
```suggestion
        ///     This does not check if the path actually exists.  It is for valid path syntax checks only.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 37]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        /// </remarks>
+        public static bool HasValidFullFilePathSyntax(this string path)
+        {
+            // Must not be null or empty
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:339]: Grammar
```suggestion
            // Must not be null or empty.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 38]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+            if (string.IsNullOrEmpty(path))
+            {
+                return false;
+            }
+
+            // Must have a drive letter
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:345]: Grammar
```suggestion
            // Must have a drive letter.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 39]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+            }
+
+            path = path.Replace(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
+
+            if (path.Contains(Path.AltDirectorySeparatorChar) is false)
+            {
+                return false;
+            }
+
+            // Must have a directory path
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:358]: Grammar
```suggestion
            // Must have a directory path.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 40]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+            if (string.IsNullOrEmpty(Path.GetDirectoryName(path)))
+            {
+                return false;
+            }
+
+            // Must have a file name with an extension
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:364]: Grammar
```suggestion
            // Must have a file name with an extension.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 41]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        /// <example>
+        /// <list type="number">
+        ///     <item>Value of <c>null</c> will return <c>true</c>.</item>
+        ///     <item><c>null</c> or <c>empty</c> will returns <c>true</c>.</item>
+        ///     <item>
+        ///         Start with a drive letter
+        ///         <para>Value of <c>C:/</c> will return <c>false</c>.</para>
+        ///     </item>
+        ///     <item>
+        ///         Contain at least 1 directory
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:383]: Grammar, SS
```suggestion
        ///         Contains at least 1 directory.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 42]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        ///         <para>will return <c>false</c>: C:/my-directory</para>
+        ///     </item>
+        ///     <item>
+        ///         Must contain a file name with file extension
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:387]: SS, grammar
```suggestion
        ///         Must contain a file name with a file extension.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 43]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        ///     <item>Value of <c>C:/my-dir</c> will return <c>true</c>.</item>
+        ///     <item>Value of <c>C:my-dir</c> will return <c>true</c>.</item>
+        ///     <item>Value of <c>C/my-dir/my-file.txt</c> will return <c>false</c>.</item>
+        ///     <item>Value of <c>//my-dir</c> will return <c>false</c>.</item>
+        ///     <item>Value of <c>./my-dir</c> will return <c>false</c>.</item>
+        ///     <item>Value of <c>../my-dir</c> will return <c>false</c>.</item>
+        /// </list>
+        /// </example>
+        /// <remarks>
+        ///     This does not check if the drive actually exists.  This is for valid path syntax checks only.
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:417]: Grammar
```suggestion
        ///     This does not check if the drive actually exists.  It is for valid path syntax checks only.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 44]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        /// <returns>True if the <paramref name="dirPath"/> is valid.</returns>
+        /// <example>
+        /// <list type="number">
+        ///     <item>Value of <c>C:/my-dir</c> will return <c>true</c>.</item>
+        ///     <item>Value of <c>C:/my-dir/</c> will return <c>true</c>.</item>
+        ///     <item>Value of <c>C:/my-dir/my-file.txt</c> will return <c>false</c>.</item>
+        /// </list>
+        /// </example>
+        /// <remarks>
+        ///     This does not check if the directory path actually exists.  This is for valid path syntax checks only.
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:457]: Grammar, SS
```suggestion
        ///     This does not check if the directory path actually exists.  It is for valid path syntax checks only.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 45]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        /// <param name="path">The path to check.</param>
+        /// <returns>True if the <paramref name="path"/> is valid.</returns>
+        /// <example>
+        /// <list type="number">
+        ///     <item>Value of <c>C:/Windows</c> will return <c>false</c>.</item>
+        ///     <item>Value of <c>//my-share</c> will return <c>true</c>.</item>
+        /// </list>
+        /// </example>
+        /// <remarks>
+        ///     This does not check if the UNC directory path actually exists.  This is for valid path syntax checks only.
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:493]: Grammar
```suggestion
        ///     This does not check if the UNC directory path actually exists.  It is for valid path syntax checks only.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 46]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+            if (path.DoesNotStartWith($@"{Path.AltDirectorySeparatorChar}{Path.AltDirectorySeparatorChar}"))
+            {
+                return false;
+            }
+
+            return path.Contains(':') is false;
+        }
+
+        /// <summary>
+        /// Returns a value indicating whether a specified substring does not occur within this string.
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:518]: Grammar
```suggestion
        /// Returns a value indicating whether or not a specified substring does not occur within this string.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 47]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+            if (string.IsNullOrEmpty(stringToSearchIn) is false && string.IsNullOrEmpty(value))
+            {
+                return true;
+            }
+
+            return !stringToSearchIn.Contains(value);
+        }
+
+        /// <summary>
+        /// Returns a value indicating whether a specified character does not occur within this string.
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:536]: Grammar
```suggestion
        /// Returns a value indicating whether or not a specified character occurs within this string.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 48]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+            if (string.IsNullOrEmpty(stringToSearchIn))
+            {
+                return true;
+            }
+
+            return !stringToSearchIn.Contains(value);
+        }
+
+        /// <summary>
+        /// Returns a value indicating whether this string only contains letters.
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:554]: Grammar
```suggestion
        /// Returns a value indicating whether or not this string contains letters.
```

File: Velaptor/PublicExtensionMethods.cs [hunk 49]
```diff
@@ -261,5 +288,280 @@ public static GlyphMetrics ApplySize(this GlyphMetrics value, float size)
...
+        /// </summary>
+        /// <param name="value">The string to check.</param>
+        /// <returns><c>true</c> if the string only contains letters.</returns>
+        public static bool OnlyContainsLetters(this string value) => value.All(character => !character.IsNotLetter());
+
+        /// <summary>
+        /// Returns a value indicating whether this string does not only contains letters.
```
Comment (kselena) [inline Velaptor/PublicExtensionMethods.cs:561]: Grammar
```suggestion
        /// Returns a value indicating whether or not this string contains letters.
```

File: Velaptor/Services/FontAtlasService.cs [hunk 50]
```diff
@@ -11,69 +11,57 @@ namespace Velaptor.Services
...
-        private readonly IFreeTypeInvoker freeTypeInvoker;
-        private readonly IFreeTypeExtensions freeTypeExtensions;
+        private readonly IFontService fontService;
         private readonly IImageService imageService;
         private readonly ISystemMonitorService monitorService;
         private readonly IFile file;
-        private readonly IntPtr freeTypeLibPtr;
+        private readonly char[] glyphChars =
+        {
+            'a', 'b', 'c', 'd', 'e',  'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
```
Comment (kselena) [inline Velaptor/Services/FontAtlasService.cs:34]: Remove extra spaces between letters etc.  Lines 36-39

File: Velaptor/Services/FontAtlasService.cs [hunk 51]
```diff
@@ -11,69 +11,57 @@ namespace Velaptor.Services
...
         private IntPtr facePtr;
-        private char[]? glyphChars;
-        private bool isDisposed;
 
         /// <summary>
         /// Initializes a new instance of the <see cref="FontAtlasService"/> class.
         /// </summary>
-        /// <param name="freeTypeInvoker">Provides low level calls to the FreeType2 library.</param>
-        /// <param name="freeTypeExtensions">Provides extensions/helpers to free type library functionality.</param>
+        /// <param name="fontService">Provides extensions/helpers to free type library functionality.</param>
```
Comment (kselena) [inline Velaptor/Services/FontAtlasService.cs:44]: FreeType
```suggestion
        /// <param name="fontService">Provides extensions/helpers to FreeType library functionality.</param>
```

File: Velaptor/Services/FontMetaDataParseResult.cs [hunk 52]
```diff
@@ -0,0 +1,55 @@
+﻿// <copyright file="FontMetaDataParseResult.cs" company="KinsonDigital">
+// Copyright (c) KinsonDigital. All rights reserved.
+// </copyright>
+
+namespace Velaptor.Services
+{
+    /// <summary>
+    /// Holds information after the result of parsing font metadata from font file paths
```
Comment (kselena) [inline Velaptor/Services/FontMetaDataParseResult.cs:8]: Grammar
```suggestion
    /// Holds information after the result of parsing font metadata from font file paths.
```

File: Velaptor/Services/TextResourceLoaderService.cs [hunk 53]
```diff
@@ -1,23 +1,33 @@
...
+    internal class TextResourceLoaderService : IEmbeddedResourceLoaderService<string>
     {
-        /// <inheritdoc cref="IEmbeddedResourceLoaderService.LoadResource"/>
+        /// <summary>
+        /// Loads embedded text file resources that match the given <param name="name"></param>.
+        /// </summary>
+        /// <param name="name">The name of the embedded text file.</param>
+        /// <returns>The embedded text file content.</returns>
+        /// <exception cref="LoadEmbeddedResourceException">
+        ///     Occurs when the embedded resource with the given <paramref name="name"/> does not exist.
```
Comment (kselena) [inline Velaptor/Services/TextResourceLoaderService.cs:29]: Indent issue?

**Review by kselena — CHANGES_REQUESTED** [review]

File: Velaptor/Services/TextResourceLoaderService.cs (hunk 53 above)
Comment (CalvinWilkinson) [reply Velaptor/Services/TextResourceLoaderService.cs:29]: The indent is ok and common practice.

File: Testing/VelaptorTests/UI/LabelTests.cs [hunk 54]
```diff
@@ -177,18 +179,18 @@ public void WidthAndHeight_WhenTextIsEmpty_CalculatesCorrectResults()
             Assert.Equal(0u, actualHeight);
         }
 
-        [Fact]
+        [Fact(Skip = "Cannot be tested until IFont is injected for mocking.")]
         public void Style_WhenSettingValue_ReturnsCorrectResult()
```
[the remark this answers is not in the document]
Comment (CalvinWilkinson) [reply Testing/VelaptorTests/UI/LabelTests.cs:183]: FYI - This is actually a property name, not a method name.  There are no parenthesis.  Also, the property that is being tested is on line 190, not on 189.  

VelFontStyle is an alias because there is a naming conflict between 2 types across the namespaces that are being used in this file. 

VelFontStyle is an alias for FontStyle and FontStyle is an enumeration which is technically a data type.

File: Velaptor/Content/Fonts/Font.cs [hunk 55]
```diff
@@ -0,0 +1,377 @@
...
+                    d.Style is FontStyle.Regular or FontStyle.Bold or FontStyle.Italic or boldItalic);
+            }
+
+            // If all for styles have been found, then were finished
+            if (AllStylesFound())
+            {
+                return;
+            }
+
+            // If all of the font styles were not found, attempt to find them in the systems directory
```
[the remark this answers is not in the document]
Comment (CalvinWilkinson) [reply Velaptor/Content/Fonts/Font.cs:309]: Quick FYI - When it comes to single line comments, it is very common and acceptable NOT to end with a period

File: Velaptor/InternalExtensionMethods.cs (hunk 24 above)
Comment (CalvinWilkinson) [reply Velaptor/InternalExtensionMethods.cs:41]: FYI - I left the word "string" at the end unchanged.  This is because this method does not check for characters, it checks for strings.

File: Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.5.md [hunk 56]
```diff
@@ -0,0 +1,114 @@
...
+11. The enumeration `TextureType` has been removed.
+12. The enumeration `TextureCreationSource` has been removed.
+13. Refactored `IContent` interface property `Path` to `FilePath` to better describe what kind of path it is.
+    - This effects the `IContent` types below.
+      - `AtlasData`
+      - `Texture`
+      - `Font`
+      - `Sound`
+14. API changes to the `IContentLoader` and `ContentLoader` types.  This was done due to extra font features needing more control over the font loading process.  This lead to using generics causing some issues with needing that finer control. 
+    - The methods `Load<T>()` and `Unload<T>` were removed and replaced with respective methods to load each type of content.
```
Comment (kselena) [inline Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.5.md:71]: SS
```suggestion
    - Removed methods `Load<T>()` and `Unload<T>` and replaced with respective methods to load each type of content.
```

File: Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.5.md [hunk 57]
```diff
@@ -0,0 +1,114 @@
...
+<h2 style="font-weight:bold" align="center">Improvements 🌟</h2>
+
+1. Changed the `Label` class to use the newly implemented default font system as a default font.
+2. Improved how content is managed increasing testability, stability and performance.
+
+---
+
+<h2 style="font-weight:bold" align="center">Other 👏</h2>
+
+1. Lots of improvements to documentation related to grammar spelling and clarity.
```
Comment (kselena) [inline Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.5.md:113]:
```suggestion
1. Lots of improvements to documentation related to grammar, spelling and clarity.
```

**Review by kselena — CHANGES_REQUESTED** [review]

File: Velaptor/Content/Caching/TextureCache.cs [hunk 58]
```diff
@@ -236,7 +262,7 @@ private void Dispose(bool disposing)
             {
                 var cacheKeys = this.textures.Keys.ToArray();
 
-                // Dispose of all textures no matter what type
+                // Dispose of all all default and non default textures
```
Comment (CalvinWilkinson) [inline Velaptor/Content/Caching/TextureCache.cs:265]: Remove the word all.  There are too many of them.

File: Testing/VelaptorTests/Helpers/AssertExtensions.cs [hunk 59]
```diff
@@ -284,21 +282,49 @@ public static void EqualWithMessage(int expected, int actual, string message)
...
+        /// <param name="expected">The expected enum.</param>
+        /// <param name="actual">The actual enum.</param>
+        /// <param name="message">The message to be shown about the failed assertion.</param>
+        public static void EqualWithMessage(Enum expected, Enum actual, string message)
         {
             var assertException = new AssertActualExpectedException(expected.ToString(), actual.ToString(), message);
 
             try
             {
                 Assert.True(expected.Equals(actual), string.IsNullOrEmpty(message) ? string.Empty : message);
```
Comment (CalvinWilkinson) [inline Testing/VelaptorTests/Helpers/AssertExtensions.cs:297]: Refactor name of all helper methods with the name `Equal` to `Equals`

Comment (CalvinWilkinson) [reply Testing/VelaptorTests/Helpers/AssertExtensions.cs:297]: Upon looking into this, it should be left as a singular word of `Equal` to match the naming of _**XUnit**_

File: Velaptor/Content/Caching/TextureCache.cs [hunk 60]
```diff
@@ -0,0 +1,276 @@
...
+        public ReadOnlyCollection<string> CacheKeys => new (this.textures.Keys.ToArray());
+
+        /// <summary>
+        /// Gets a texture using the given <paramref name="textureFilePath"/>.
+        /// <para>
+        ///     If the given <paramref name="textureFilePath"/> is a <c>.ttf</c> font file, then the texture will be a font atlas
+        ///     texture created from the font.  Font file paths must include metadata.
+        /// </para>
+        /// <para>
+        ///     If the item has not been retrieved before, it will create it and then cache it for fast retrieval
```
Comment (kselena) [inline Velaptor/Content/Caching/TextureCache.cs:87]: SS
```suggestion
        ///     If the item has not been previously created, the <see cref="TextureCache"/> class will retrieve it, and cache it for fast retrieval.
```

File: Velaptor/Content/Caching/TextureCache.cs [hunk 61]
```diff
@@ -0,0 +1,276 @@
...
+        ///     on the next call.
```
Comment (kselena) [inline Velaptor/Content/Caching/TextureCache.cs:88]: Delete line
```suggestion
```

File: Velaptor/Content/SoundPathResolver.cs [hunk 62]
```diff
@@ -40,7 +40,7 @@ public SoundPathResolver(IDirectory directory)
         ///     file will be loaded, not the '.mp3' file.
         /// </para>
         /// <para>
-        ///     If no '.ogg' file exists but a '.mp3' file does not, then the '.mp3' file will be loaded.
+        ///     If no <c>.ogg</c> file exists but a <c>.mp3</c> file does, then the <c>.mp3</c> file will be loaded.
```
Comment (kselena) [inline Velaptor/Content/SoundPathResolver.cs:43]: Grammar
```suggestion
        ///     If no <c>.ogg</c> file exists but an <c>.mp3</c> file does, then the <c>.mp3</c> file will be loaded.
```

File: Velaptor/Content/Texture.cs [hunk 63]
```diff
@@ -25,15 +25,14 @@ public sealed class Texture : ITexture
 
         /*NOTE:
          * This flag is for the purpose of unit testing.  This flag gets set in one location and that is
```
Comment (kselena) [inline Velaptor/Content/Texture.cs:27]: SS
```suggestion
         * This flag is for the purpose of unit testing and gets set in the finalizer  location.
```

File: Velaptor/Content/Texture.cs [hunk 64]
```diff
@@ -25,15 +25,14 @@ public sealed class Texture : ITexture
...
-         * the finalizer.  This then gets checked to see if it is false in the Dispose() method.
+         * the finalizer.  This gets checked to see if it is false in the Dispose() method.
```
Comment (kselena) [inline Velaptor/Content/Texture.cs:28]: SS
```suggestion
         * The flag gets checked to see if it is false in the Dispose() method.
```

File: Velaptor/Content/Texture.cs [hunk 65]
```diff
@@ -25,15 +25,14 @@ public sealed class Texture : ITexture
...
          *
          * If the finalizer is false and the Texture is pooled, it will then allow the PooledDisposalException
          * to be thrown.
          *
-         * An issue arises when running enough unit tests together with this class being included in those tests
-         * When a lot of tests are ran, the finalizers is being invoked which then in turn invokes the Dispose()
-         * method. This in turn then throws the exception which is not expected in the unit tests which fails the
-         * unit test.
+         * An issue arises when running enough unit tests together with this class being included in those tests.
```
Comment (kselena) [inline Velaptor/Content/Texture.cs:33]: Grammar
```suggestion
         * An issue arises when running enough unit tests together with this class included in those tests.
```

File: Velaptor/Content/Texture.cs [hunk 66]
```diff
@@ -25,15 +25,14 @@ public sealed class Texture : ITexture
...
+         * When a lot of tests are ran, the finalizers are being invoked which in turn invokes the Dispose()
```
Comment (kselena) [inline Velaptor/Content/Texture.cs:34]: Grammar
```suggestion
         * When a lot of tests are run, the finalizers are being invoked which, in turn, invokes the Dispose()
```

File: Velaptor/Graphics/ImageData.cs [hunk 67]
```diff
@@ -142,15 +175,13 @@ public bool Equals(ImageData other)
...
-            if (obj is not ImageData imageData)
-            {
-                return false;
-            }
+        public override bool Equals(object? obj) => obj is ImageData imageData && Equals(imageData);
 
-            return Equals(imageData);
-        }
+        /// <summary>
+        /// Returns a value indicating if the <see cref="ImageData"/> contents are empty.
```
Comment (kselena) [inline Velaptor/Graphics/ImageData.cs:181]: SS
```suggestion
        /// Returns a value indicating whether or not the <see cref="ImageData"/> contents are empty.
```

**Review by kselena — CHANGES_REQUESTED** [review]

File: Testing/VelaptorTests/NativeInterop/GLFW/GLFWMonitorsTests.cs [hunk 68]
```diff
@@ -139,13 +139,55 @@ public void Ctor_WhenInvoked_SystemMonitorsRefreshed()
...
             var actual = monitors.SystemMonitors;
 
             // Assert
             Assert.Equal(expectedMonitorA, actual[0]);
             Assert.Equal(expectedMonitorB, actual[1]);
         }
         #endregion
+
+        #region Method Tests
+
```
Comment (CalvinWilkinson) [inline Testing/VelaptorTests/NativeInterop/GLFW/GLFWMonitorsTests.cs:152]: Remove extra space after `#region`

File: Velaptor/Content/AtlasData.cs [hunk 69]
```diff
@@ -35,22 +35,40 @@ public sealed class AtlasData : IAtlasData
         /// <param name="atlasSubTextureData">The sub texture data of all sub textures in the atlas.</param>
         /// <param name="dirPath">The path to the content.</param>
         /// <param name="atlasName">The name of the atlas.</param>
+        /// <exception cref="ArgumentNullException"></exception>
```
Comment (CalvinWilkinson) [inline Velaptor/Content/AtlasData.cs:38]: Add code docs to the exception tag

File: Velaptor/Input/KeyboardState.cs [hunk 70]
```diff
@@ -326,30 +326,25 @@ public char KeyToChar(KeyCode key)
...
+            {
+                return NoShiftSymbolCharacters[key];
+            }
 
-                // When the shift is is up, the standard number keys return numbers.
-                if (StandardNumberKeys.Contains(key))
-                {
-                    return NoShiftStandardNumberCharacters[key];
-                }
+            // When the shift is is up, the standard number keys return numbers.
```
Comment (CalvinWilkinson) [inline Velaptor/Input/KeyboardState.cs:344]: Refactor comment as below:

```suggestion
            // When the shift is up, the standard number keys return numbers.
```

File: Velaptor/Content/Texture.cs (hunk 63 above)
Comment (CalvinWilkinson) [reply Velaptor/Content/Texture.cs:27]: I did some investigation and discovered that this text and the associated bool variable can be removed and is not required anymore.  So I deleted it all.

File: Testing/VelaptorTests/Content/ContentPathResolverTests.cs [hunk 71]
```diff
@@ -93,8 +97,10 @@ public void ResolveFilePath_WhenInvoked_ResolvesContentFilePath(string contentNa
         public void ResolveDirPath_WhenInvoked_ResolvesContentDirPath()
```
[the remark this answers is not in the document]
Comment (CalvinWilkinson) [reply Testing/VelaptorTests/Content/ContentPathResolverTests.cs:97]: This is a very unique case and does not need to be renamed

**Review by kselena — APPROVED** [review]
